### ISSUE TITLE
Port to beta version of Material UI

### ISSUE THREAD

**Issue by drcode** [forward-blockchain/qlkit-material-ui#2]
Here is the page for the new version: https://material-ui-next.com
Not sure how hard/easy this will be.
Need to make sure advanced compilation still works after the change.

**Comment by craig-ludington** [comment]
Should we update cljsjs?  Latest there is `v0.19.2`

**Comment by craig-ludington** [comment]
Pull requests:

https://github.com/forward-blockchain/qlkit#6
https://github.com/forward-blockchain/qlkit-renderer#2
https://github.com/forward-blockchain/qlkit-material-ui/pull/3
https://github.com/forward-blockchain/qlkit-todo-demo/pull/1
https://github.com/cljsjs/packages/pull/1493
